### ISSUE TITLE
Error after 2.0.1b upgrade

### ISSUE THREAD

**Issue by jes1417** [claytonjn/hass-circadian_lighting#115]
I am getting errors after the second restart of HA everything seemed ok after the upgrade the system booted with no errors but I noticed lights were not changing so I ended up rebooting again for a different reason and got these errors

![Screenshot_20200906-204550.png](https://user-images.githubusercontent.com/38092747/92341223-a7367480-f082-11ea-842e-9056bf75ec77.png)

```
Log Details (ERROR)

Logger: homeassistant.setup
Source: custom_components/circadian_lighting/__init__.py:295
First occurred: 8:45:11 PM (1 occurrences)
Last logged: 8:45:11 PM

Error during setup of component circadian_lightingTraceback (most recent call last): 
File "/usr/src/homeassistant/homeassistant/setup.py", line 191, in _async_setup_component result = await task 
File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) 
File "/config/custom_components/circadian_lighting/__init__.py", line 107, in setup hass.data[DOMAIN] = CircadianLighting( 
File "/config/custom_components/circadian_lighting/__init__.py", line 156, in __init__ self._percent = self.calc_percent() 
File "/config/custom_components/circadian_lighting/__init__.py", line 295, in calc_percent a = (y - k) / (h - x) ** 2 

UnboundLocalError: local variable 'k' referenced before assignment

```

Here is my config

```
circadian_lighting:
  min_colortemp: 2000
  max_colortemp: 6535
  sunrise_offset: +01:00:00
  sunset_offset: +01:00:00
```
And switch
```
# Circadian Lighting
  - platform: circadian_lighting
    name: Circadian House
    lights_ct:
      - light.mommy_s_light
      - light.daddy_s_light
      - light.kitchen_lights
      - light.dining_lights
      - light.entry_lights
      - light.bar_light
      - light.living_room
    lights_brightness:
      - light.kids_room_light
    min_brightness: 5
    max_brightness: 100

  - platform: circadian_lighting
    name: Circadian Bathrooms
    lights_ct:
      - light.master_bath_lights
      - light.downstairs_bath
      - light.hallway_lights
      - light.master_closet_2
    lights_brightness:
      - light.kids_bathroom_lights
      - light.laundry_light
    min_brightness: 30
    max_brightness: 100
      
  - platform: circadian_lighting
    name: Circadian Utilities
    lights_ct:
      - light.porch
      - light.back_porch
    disable_brightness_adjust: true
```

![Screenshot_20200906-205405.png](https://user-images.githubusercontent.com/38092747/92341381-24fa8000-f083-11ea-9ae9-f8576a174f56.png)

**Comment by jes1417** [comment]
Ok not sure what happened on the upgrade but I re-installed through have and rebooted and everything came back.🤦

**Comment by jes1417** [comment]
Ok so errors are back on the 0.115.0b release, I have tried reinstalling and rebooting several times but I am still getting the same errors.


```
Log Details (ERROR)

Logger: homeassistant.setup
Source: custom_components/circadian_lighting/__init__.py:295
First occurred: 8:27:48 PM (1 occurrences)
Last logged: 8:27:48 PM

Error during setup of component circadian_lightingTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component result = await task File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/circadian_lighting/__init__.py", line 107, in setup hass.data[DOMAIN] = CircadianLighting( File "/config/custom_components/circadian_lighting/__init__.py", line 156, in __init__ self._percent = self.calc_percent() File "/config/custom_components/circadian_lighting/__init__.py", line 295, in calc_percent a = (y - k) / (h - x) ** 2 UnboundLocalError: local variable 'k' referenced before assignment

```
```
Log Details (ERROR)

Logger: homeassistant.setup
Source: setup.py:280
First occurred: 8:27:50 PM (3 occurrences)
Last logged: 8:27:50 PM

Unable to prepare setup for platform circadian_lighting.switch: Unable to set up component.

```

**Comment by claytonjn** [comment]
@basnijholt it looks like in these instances now_ts is not falling between sunrise and sunset, or vise versa. I don't see anything in the simplified code that should have changed this; it might be helpful to get some debug logging put back in so that we can see exactly what values are being used for the comparisons. Do you want to handle that in #114 to make merging easier? Or am I missing a logic change that might be causing this?

**Comment by basnijholt** [comment]
I didn't get notifications of these issues, but now I've turned it on. It is indeed that 
```
today[SUN_EVENT_SUNRISE] < now_ts < today[SUN_EVENT_SUNSET] is False
```
and
```
today[SUN_EVENT_SUNSET] < now_ts < today[SUN_EVENT_SUNRISE] is False
```
I am looking into it now! And I agree that some more logging would be useful ;)

**Comment by basnijholt** [comment]
@jes1417, could you please try the code of https://github.com/claytonjn/hass-circadian_lighting/pull/116?

**Comment by jes1417** [comment]
System started up normal, no more errors.

**Comment by basnijholt** [comment]
Great! Then I think @claytonjn  can merge that PR

**Comment by basnijholt** [comment]
Let's close this issue 😄

**Comment by claytonjn** [comment]
I was waiting to close until I do a stable release, but I guess since the issue was introduced in beta and fixed in beta it makes more sense to close now :)

**Comment by jes1417** [comment]
I am still seeing some errors in the logs from this component

```Logger: homeassistant
Source: custom_components/circadian_lighting/__init__.py:295
First occurred: 7:03:31 PM (8 occurrences)
Last logged: 7:38:31 PM

Error doing job: Task exception was never retrievedTraceback (most recent call last): File "/config/custom_components/circadian_lighting/__init__.py", line 318, in update self._percent = self.calc_percent() File "/config/custom_components/circadian_lighting/__init__.py", line 295, in calc_percent a = (y - k) / (h - x) ** 2 UnboundLocalError: local variable 'k' referenced before assignment
```

**Comment by basnijholt** [comment]
@jes1417, that is weird I cannot reproduce this problem at all.

Could you share your configuration of the `circadian_lighting` integration and the `switch`?

**Comment by basnijholt** [comment]
@jes1417, is it possible for you to try https://github.com/claytonjn/hass-circadian_lighting/pull/119/files?

**Comment by jes1417** [comment]
I will try this but I am not convinced it not something else with my setup creating this issue. I was having weird issues with my harmony hub and after rebooting the hub then rebooting hass this component was able to start... 

```
circadian_lighting:
  min_colortemp: 2000
  max_colortemp: 6535
  sunrise_offset: +01:00:00
  sunset_offset: +01:00:00
```
``` 
 - platform: circadian_lighting
    name: Circadian House
    lights_ct:
      - light.mommy_s_light
      - light.daddy_s_light
      - light.kitchen_lights
      - light.dining_lights
      - light.entry_lights
      - light.bar_light
      - light.living_room
    lights_brightness:
      - light.kids_room_light
    min_brightness: 5
    max_brightness: 100

  - platform: circadian_lighting
    name: Circadian Bathrooms
    lights_ct:
      - light.master_bath_lights
      - light.downstairs_bath
      - light.hallway_lights
      - light.master_closet_2
    lights_brightness:
      - light.kids_bathroom_lights
      - light.laundry_light
    min_brightness: 15
    max_brightness: 100
      
  - platform: circadian_lighting
    name: Circadian Utilities
    lights_ct:
      - light.porch
      - light.back_porch
    disable_brightness_adjust: true
```

**Comment by jes1417** [comment]
It won't start with the changes made.

```
Log Details (ERROR)

Logger: homeassistant.setup
Source: custom_components/circadian_lighting/__init__.py:157
First occurred: 9:03:49 AM (1 occurrences)
Last logged: 9:03:49 AM

Error during setup of component circadian_lightingTraceback (most recent call last): File "/usr/src/homeassistant/homeassistant/setup.py", line 213, in _async_setup_component result = await task File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run result = self.fn(*self.args, **self.kwargs) File "/config/custom_components/circadian_lighting/__init__.py", line 108, in setup hass.data[DOMAIN] = CircadianLighting( File "/config/custom_components/circadian_lighting/__init__.py", line 157, in __init__ self._percent = self.calc_percent() AttributeError: 'CircadianLighting' object has no attribute 'calc_percent'

```

**Comment by jes1417** [comment]
Reverting to the previous change got it to start again.

**Comment by basnijholt** [comment]
oops, I accidentally change the method name I fix it now.
